receivers:
  otlp:
    protocols:
      http: {}

processors:
  batch:
    timeout: 5s
    send_batch_size: 10000

exporters:
 clickhouse:
    endpoint: tcp://clickhouse:9000
    database: otel
    username: default
    password: ""
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
