version: "3.9"
services:
  api:
    build: ./app
    container_name: otel-fastapi
    environment:
      OTEL_SERVICE_NAME: pipes-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
    ports:
      - "8000:8000"
    volumes:
      - ./app/app:/app/app:cached
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"   # OTLP HTTP

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: otel
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    volumes:
      - ch_data:/var/lib/clickhouse
    # keep resources reasonable on laptops
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  ch_data:
