version: "3.9"
services:
  api:
    build: ./app
    container_name: otel-fastapi
    environment:
      OTEL_SERVICE_NAME: pipes-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
    ports:
      - "8000:8000"
    volumes:
      - ./app/app:/app/app:cached
    depends_on:
      - collector

  otel-collector:
      image: otel/opentelemetry-collector-contrib:0.104.0
      command: ["--config=/etc/otel-collector-config.yaml"]
      volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      depends_on:
        clickhouse:
          condition: service_healthy
      ports:
        - "4317:4317"   # gRPC OTLP
        - "4318:4318"   # HTTP OTLP
        - "8888:8888"   # Collector metrics

  clickhouse:
      image: clickhouse/clickhouse-server:23.8
      ports:
        - "8123:8123"   # HTTP
        - "9000:9000"   # Native
      volumes:
        - ch_data:/var/lib/clickhouse
      healthcheck:
        test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
        interval: 5s
        timeout: 3s
        retries: 5

volumes:
  ch_data:
