receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  clickhouse:
    endpoint: https://w2mi3qy9ce.me-central-1.aws.clickhouse.cloud:8443
    database: otel_z
    username: default
    password: "tgKnfQyi4~j18"
  
  otlp/hyperdx:
    endpoint: "https://in-otel.hyperdx.io:4317"
    headers:
      authorization: "2332b044-2469-4bc1-8fba-b0867470eb84"

  debug:
    verbosity: normal

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/hyperdx, debug]  # Send to both!
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/hyperdx, debug]   # Send to both!
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp/hyperdx, debug]    # Send to both!