receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  clickhouse:
    endpoint: https://g0kx3zs84v.germanywestcentral.azure.clickhouse.cloud:8443
    database: otel
    username: default
    password: "snC4MR1F9~anw"
  debug:
    verbosity: normal

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, debug]